# Generated by Django 2.2.10 on 2020-04-21 17:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mappage',
            old_name='introduction',
            new_name='intro',
        ),
        migrations.RenameField(
            model_name='mapsindexpage',
            old_name='introduction',
            new_name='intro',
        ),
        migrations.AlterField(
            model_name='mappage',
            name='lat_long',
            field=models.CharField(help_text='Comma separated long/lat. (Ex. -21.939182, 64.144367)', max_length=36, validators=[django.core.validators.RegexValidator(code='invalid_lat_long', message='Lat Long must be a comma-separated numeric lat and long', regex='^(\\-?\\d+(\\.\\d+)?),\\s*(\\-?\\d+(\\.\\d+)?)$')]),
        ),
    ]
