# Generated by Django 2.2.10 on 2020-04-21 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0002_auto_20200421_1954'),
    ]

    operations = [
        migrations.AddField(
            model_name='mappage',
            name='zoom',
            field=models.TextField(blank=True, help_text='Zoom level. Must be between 0 and 18', max_length=2),
        ),
    ]
