# Generated by Django 2.2.10 on 2020-04-21 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0003_mappage_zoom'),
    ]

    operations = [
        migrations.CreateModel(
            name='MapStyle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'map styles',
            },
        ),
    ]
