# Generated by Django 2.2.10 on 2020-04-22 07:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0005_mappage_map_styles'),
    ]

    operations = [
        migrations.AddField(
            model_name='mappage',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='Map date'),
        ),
        migrations.RemoveField(
            model_name='mappage',
            name='map_styles',
        ),
        migrations.AddField(
            model_name='mappage',
            name='map_styles',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='maps.MapStyle'),
        ),
    ]
