# Generated by Django 2.2.10 on 2020-04-22 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0006_auto_20200422_0921'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mappage',
            old_name='map_styles',
            new_name='map_style',
        ),
    ]
