# Generated by Django 2.2.10 on 2020-04-22 07:40

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0007_auto_20200422_0930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mappage',
            name='image',
            field=models.ForeignKey(blank=True, help_text='Map thumbnail', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='base.CustomImage'),
        ),
        migrations.AlterField(
            model_name='mappage',
            name='lat_long',
            field=models.CharField(help_text='Comma separated long/lat. (Ex. Torino is 7.676111, 45.079167)', max_length=36, validators=[django.core.validators.RegexValidator(code='invalid_lat_long', message='Lat Long must be a comma-separated numeric long and lat', regex='^(\\-?\\d+(\\.\\d+)?),\\s*(\\-?\\d+(\\.\\d+)?)$')]),
        ),
    ]
