# Generated by Django 2.2.10 on 2020-04-22 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0009_auto_20200422_1019'),
    ]

    operations = [
        migrations.AddField(
            model_name='mappage',
            name='layer',
            field=models.TextField(blank=True, help_text='GeoServer WMS layer name'),
        ),
    ]
