# Generated by Django 2.2.10 on 2020-04-07 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_projectpage_featured'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectpage',
            old_name='featured',
            new_name='is_featured',
        ),
    ]
