# Generated by Django 2.2.10 on 2020-04-07 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_auto_20200407_1651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectpage',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Featured projects will appear on the home page'),
        ),
    ]
