# Generated by Django 2.2.10 on 2020-04-09 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personpage',
            name='biography',
            field=models.CharField(blank=True, max_length=1024),
        ),
    ]
