# Generated by Django 2.2.10 on 2020-04-09 15:42

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0002_auto_20200409_1738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personpage',
            name='biography',
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
    ]
