# Generated by Django 2.2.10 on 2020-03-05 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_auto_20200305_1627'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FooterText',
        ),
        migrations.DeleteModel(
            name='People',
        ),
    ]
